require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SeriesController do

  def mock_series(stubs={})
    @mock_series ||= mock_model(Series, stubs).as_null_object
  end

=begin
  describe "GET index" do
    it "assigns all series as @series" do
      Series.stub(:all) { [mock_series] }
      get :index
      assigns(:series).should eq([mock_series])
    end
  end

  describe "GET show" do
    it "assigns the requested series as @series" do
      Series.stub(:find).with(:permalink => "37") { mock_series }
      get :show, :permalink => "37"
      assigns(:series).should be(mock_series)
    end
  end
=end

end
